# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.component import Component
from openapi_server import util

from openapi_server.models.component import Component  # noqa: E501

class ComponentTemplate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, label=None, component=None):  # noqa: E501
        """ComponentTemplate - a model defined in OpenAPI

        :param id: The id of this ComponentTemplate.  # noqa: E501
        :type id: str
        :param label: The label of this ComponentTemplate.  # noqa: E501
        :type label: str
        :param component: The component of this ComponentTemplate.  # noqa: E501
        :type component: Component
        """
        self.openapi_types = {
            'id': str,
            'label': str,
            'component': Component
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'component': 'component'
        }

        self._id = id
        self._label = label
        self._component = component

    @classmethod
    def from_dict(cls, dikt) -> 'ComponentTemplate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ComponentTemplate of this ComponentTemplate.  # noqa: E501
        :rtype: ComponentTemplate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ComponentTemplate.


        :return: The id of this ComponentTemplate.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComponentTemplate.


        :param id: The id of this ComponentTemplate.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this ComponentTemplate.


        :return: The label of this ComponentTemplate.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ComponentTemplate.


        :param label: The label of this ComponentTemplate.
        :type label: str
        """

        self._label = label

    @property
    def component(self):
        """Gets the component of this ComponentTemplate.


        :return: The component of this ComponentTemplate.
        :rtype: Component
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this ComponentTemplate.


        :param component: The component of this ComponentTemplate.
        :type component: Component
        """

        self._component = component
