/* tslint:disable */
/* eslint-disable */
/**
 * Rig and Rack API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Component
 */
export interface Component {
    /**
     * 
     * @type {string}
     * @memberof Component
     */
    'id'?: string;
    /**
     * 
     * @type {object}
     * @memberof Component
     */
    'input'?: object;
    /**
     * 
     * @type {object}
     * @memberof Component
     */
    'output'?: object;
    /**
     * 
     * @type {object}
     * @memberof Component
     */
    'config'?: object | null;
    /**
     * 
     * @type {object}
     * @memberof Component
     */
    'ui'?: object;
}
/**
 * 
 * @export
 * @interface ComponentConfig
 */
export interface ComponentConfig {
    /**
     * 
     * @type {Component}
     * @memberof ComponentConfig
     */
    'component'?: Component;
    /**
     * 
     * @type {object}
     * @memberof ComponentConfig
     */
    'definition'?: object;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface Rack
 */
export interface Rack {
    /**
     * 
     * @type {string}
     * @memberof Rack
     */
    'id'?: string;
    /**
     * 
     * @type {Array<Component>}
     * @memberof Rack
     */
    'components'?: Array<Component>;
    /**
     * 
     * @type {object}
     * @memberof Rack
     */
    'config'?: object;
}
/**
 * 
 * @export
 * @interface Rig
 */
export interface Rig {
    /**
     * 
     * @type {Array<ComponentConfig>}
     * @memberof Rig
     */
    'componentConfigs'?: Array<ComponentConfig>;
    /**
     * 
     * @type {Array<Rack>}
     * @memberof Rig
     */
    'racks'?: Array<Rack>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new rack
         * @param {Rack} rack The rack to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRack: async (rack: Rack, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rack' is not null or undefined
            assertParamExists('createRack', 'rack', rack)
            const localVarPath = `/racks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rack, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a specific rack
         * @param {string} rackId The ID of the rack to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRackById: async (rackId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rackId' is not null or undefined
            assertParamExists('deleteRackById', 'rackId', rackId)
            const localVarPath = `/racks/{rackId}`
                .replace(`{${"rackId"}}`, encodeURIComponent(String(rackId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a specific rack
         * @param {string} rackId The ID of the rack to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRackById: async (rackId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rackId' is not null or undefined
            assertParamExists('getRackById', 'rackId', rackId)
            const localVarPath = `/racks/{rackId}`
                .replace(`{${"rackId"}}`, encodeURIComponent(String(rackId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a list of racks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRacks: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/racks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve the rig
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRig: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/rig`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a specific rack
         * @param {string} rackId The ID of the rack to update
         * @param {Rack} rack The updated rack data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRackById: async (rackId: string, rack: Rack, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rackId' is not null or undefined
            assertParamExists('updateRackById', 'rackId', rackId)
            // verify required parameter 'rack' is not null or undefined
            assertParamExists('updateRackById', 'rack', rack)
            const localVarPath = `/racks/{rackId}`
                .replace(`{${"rackId"}}`, encodeURIComponent(String(rackId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rack, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new rack
         * @param {Rack} rack The rack to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRack(rack: Rack, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rack>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRack(rack, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete a specific rack
         * @param {string} rackId The ID of the rack to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRackById(rackId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRackById(rackId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Retrieve a specific rack
         * @param {string} rackId The ID of the rack to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRackById(rackId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rack>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRackById(rackId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Retrieve a list of racks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRacks(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Rack>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRacks(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Retrieve the rig
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRig(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRig(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update a specific rack
         * @param {string} rackId The ID of the rack to update
         * @param {Rack} rack The updated rack data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRackById(rackId: string, rack: Rack, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rack>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRackById(rackId, rack, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new rack
         * @param {Rack} rack The rack to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRack(rack: Rack, options?: any): AxiosPromise<Rack> {
            return localVarFp.createRack(rack, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a specific rack
         * @param {string} rackId The ID of the rack to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRackById(rackId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteRackById(rackId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a specific rack
         * @param {string} rackId The ID of the rack to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRackById(rackId: string, options?: any): AxiosPromise<Rack> {
            return localVarFp.getRackById(rackId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a list of racks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRacks(options?: any): AxiosPromise<Array<Rack>> {
            return localVarFp.getRacks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve the rig
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRig(options?: any): AxiosPromise<Rig> {
            return localVarFp.getRig(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a specific rack
         * @param {string} rackId The ID of the rack to update
         * @param {Rack} rack The updated rack data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRackById(rackId: string, rack: Rack, options?: any): AxiosPromise<Rack> {
            return localVarFp.updateRackById(rackId, rack, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new rack
     * @param {Rack} rack The rack to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createRack(rack: Rack, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createRack(rack, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a specific rack
     * @param {string} rackId The ID of the rack to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteRackById(rackId: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteRackById(rackId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a specific rack
     * @param {string} rackId The ID of the rack to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRackById(rackId: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRackById(rackId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a list of racks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRacks(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRacks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve the rig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRig(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRig(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a specific rack
     * @param {string} rackId The ID of the rack to update
     * @param {Rack} rack The updated rack data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateRackById(rackId: string, rack: Rack, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateRackById(rackId, rack, options).then((request) => request(this.axios, this.basePath));
    }
}


