# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gen_api.models.base_model_ import Model
from gen_api.models.component import Component
from gen_api import util

from gen_api.models.component import Component  # noqa: E501

class ComponentConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, component=None, definition=None):  # noqa: E501
        """ComponentConfig - a model defined in OpenAPI

        :param component: The component of this ComponentConfig.  # noqa: E501
        :type component: Component
        :param definition: The definition of this ComponentConfig.  # noqa: E501
        :type definition: object
        """
        self.openapi_types = {
            'component': Component,
            'definition': object
        }

        self.attribute_map = {
            'component': 'component',
            'definition': 'definition'
        }

        self._component = component
        self._definition = definition

    @classmethod
    def from_dict(cls, dikt) -> 'ComponentConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ComponentConfig of this ComponentConfig.  # noqa: E501
        :rtype: ComponentConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def component(self):
        """Gets the component of this ComponentConfig.


        :return: The component of this ComponentConfig.
        :rtype: Component
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this ComponentConfig.


        :param component: The component of this ComponentConfig.
        :type component: Component
        """

        self._component = component

    @property
    def definition(self):
        """Gets the definition of this ComponentConfig.


        :return: The definition of this ComponentConfig.
        :rtype: object
        """
        return self._definition

    @definition.setter
    def definition(self, definition):
        """Sets the definition of this ComponentConfig.


        :param definition: The definition of this ComponentConfig.
        :type definition: object
        """

        self._definition = definition
