openapi: 3.0.3
info:
  title: aifi - OpenAPI 3.0
  description: |-
    ## Model Diagram
    ```mermaid
    classDiagram
    class Device {
        string id
        string label
    }
    class Rack {
        string id
        string label
        string description
        %% the below property is an array with cardinality [0..*]
        string hiddenComponents
    }
    class UiSetting {
        string id
        string label
        boolean hidden
        string dataType
        string uiType
        object defaultValue
        object initialValue
    }
    class DeviceFactory {
        string id
        string label
        object apiConfiguration
        string version
    }

    class Asset {
        string id
        string type
        string label
        string description
        string storageLocation
        %% the below property is an array with cardinality [0..*]
        string previewLocations
    }
    
    class Rig { 
    }
    class Connection {
        string id
        string label
        string description
        string type
        boolean required
        boolean allowMultiple
    }
    class KeyValue {
        string key
        string value
    }
    class Error {
        string message
        integer code
    }

    Rack "1" --> "0..*" Device : devices
    Rig "1" --> "0..*" DeviceFactory : factories
    Rig  "1" --> "0..*" KeyValue : config
    Rig  "1" --> "0..*" KeyValue : secrets
    DeviceFactory "1" --> "0..1"  Rack: rackAsDevice
    Rack "1" --> "0..*"  Connection: output
    Rig "1" --> "0..*" Rack : racks
    DeviceFactory "1" --> "0..*" Asset : assets
    Device "1" --> "1"  DeviceFactory: definition
    Device "1" --> "0..*"  UiSetting: uiSettingOverrides
    DeviceFactory "1" --> "0..*"  UiSetting: uiSettings
    DeviceFactory "1" --> "0..*"  Connection: input
    DeviceFactory "1" --> "0..*"  Connection: output
    ```
  version: 1.0.0
paths:
  /racks:
    get:
      summary: Retrieve a list of racks
      operationId: getRacks
      responses:
        '200':
          description: A list of racks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rack'
    post:
      summary: Create a new rack
      operationId: createRack
      requestBody:
        description: The rack to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rack'
      responses:
        '201':
          description: Rack created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rack'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /racks/{rackId}:
    get:
      summary: Retrieve a specific rack
      operationId: getRackById
      parameters:
        - name: rackId
          in: path
          description: The ID of the rack to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single rack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rack'
        '404':
          description: Rack not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a specific rack
      operationId: updateRackById
      parameters:
        - name: rackId
          in: path
          description: The ID of the rack to update
          required: true
          schema:
            type: string
      requestBody:
        description: The updated rack data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rack'
      responses:
        '200':
          description: Rack updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rack'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Rack not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a specific rack
      operationId: deleteRackById
      parameters:
        - name: rackId
          in: path
          description: The ID of the rack to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Rack deleted successfully
        '404':
          description: Rack not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /rig:
    get:
      summary: Retrieve the rig
      operationId: getRig
      responses:
        '200':
          description: The rig object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rig'

components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        definition:
          $ref: '#/components/schemas/DeviceFactory'
        uiSettingOverrides:
          type: array
          items:
            $ref: '#/components/schemas/UiSetting'
    DeviceFactory:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        apiConfiguration:
          type: object
        version:
          type: string
        assets:
          type: array
          items:
            $ref: '#/components/schemas/Asset'
        uiSettings:
          type: array
          items:
            $ref: '#/components/schemas/UiSetting'
        input:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        output:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
    Rack:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        description:
          type: string
        hiddenComponents:
          type: array
          items:
            type: string
        devices:
          type: array
          items:
            $ref: '#/components/schemas/Device'
        output:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
    UiSetting:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        hidden:
          type: boolean
        dataType:
          type: string
        uiType:
          type: string
        defaultValue:
          type: object
        initialValue:
          type: object
    Asset:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        label:
          type: string
        description:
          type: string
        storageLocation:
          type: string
        previewLocations:
          type: array
          items:
            type: string
    Connection:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        description:
          type: string
        type:
          type: string
        required:
          type: boolean
        allowMultiple:
          type: boolean
    KeyValue:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
    Rig:
      type: object
      properties:
        factories:
          type: array
          items:
            $ref: '#/components/schemas/DeviceFactory'
        config:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        secrets:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        racks:
          type: array
          items:
            $ref: '#/components/schemas/Rack'


