# coding: utf-8

import sys
from setuptools import setup, find_packages

NAME = "gen_api"
VERSION = "1.0.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "connexion>=2.0.2",
    "swagger-ui-bundle>=0.0.2",
    "python_dateutil>=2.6.0"
]

setup(
    name=NAME,
    version=VERSION,
    description="Rig and Rack API",
    author_email="",
    url="",
    keywords=["OpenAPI", "Rig and Rack API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    package_data={'': ['./gen_api/openapi/openapi.yaml']},
    include_package_data=True,
    entry_points={
        'console_scripts': ['gen_api=gen_api.__main__:main']},
    long_description="""\
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    """
)

