# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from aifi.api.models.base_model_ import Model
from aifi.api.models.component_definition import ComponentDefinition
from aifi.api.models.connection import Connection
from aifi.api.models.ui_setting import UiSetting
from aifi.api import util

from aifi.api.models.component_definition import ComponentDefinition  # noqa: E501
from aifi.api.models.connection import Connection  # noqa: E501
from aifi.api.models.ui_setting import UiSetting  # noqa: E501

class Component(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, ui_settings=None, input=None, output=None, component_definition=None):  # noqa: E501
        """Component - a model defined in OpenAPI

        :param id: The id of this Component.  # noqa: E501
        :type id: str
        :param ui_settings: The ui_settings of this Component.  # noqa: E501
        :type ui_settings: List[UiSetting]
        :param input: The input of this Component.  # noqa: E501
        :type input: List[Connection]
        :param output: The output of this Component.  # noqa: E501
        :type output: List[Connection]
        :param component_definition: The component_definition of this Component.  # noqa: E501
        :type component_definition: ComponentDefinition
        """
        self.openapi_types = {
            'id': str,
            'ui_settings': List[UiSetting],
            'input': List[Connection],
            'output': List[Connection],
            'component_definition': ComponentDefinition
        }

        self.attribute_map = {
            'id': 'id',
            'ui_settings': 'uiSettings',
            'input': 'input',
            'output': 'output',
            'component_definition': 'componentDefinition'
        }

        self._id = id
        self._ui_settings = ui_settings
        self._input = input
        self._output = output
        self._component_definition = component_definition

    @classmethod
    def from_dict(cls, dikt) -> 'Component':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Component of this Component.  # noqa: E501
        :rtype: Component
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Component.


        :return: The id of this Component.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Component.


        :param id: The id of this Component.
        :type id: str
        """

        self._id = id

    @property
    def ui_settings(self):
        """Gets the ui_settings of this Component.


        :return: The ui_settings of this Component.
        :rtype: List[UiSetting]
        """
        return self._ui_settings

    @ui_settings.setter
    def ui_settings(self, ui_settings):
        """Sets the ui_settings of this Component.


        :param ui_settings: The ui_settings of this Component.
        :type ui_settings: List[UiSetting]
        """

        self._ui_settings = ui_settings

    @property
    def input(self):
        """Gets the input of this Component.


        :return: The input of this Component.
        :rtype: List[Connection]
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this Component.


        :param input: The input of this Component.
        :type input: List[Connection]
        """

        self._input = input

    @property
    def output(self):
        """Gets the output of this Component.


        :return: The output of this Component.
        :rtype: List[Connection]
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this Component.


        :param output: The output of this Component.
        :type output: List[Connection]
        """

        self._output = output

    @property
    def component_definition(self):
        """Gets the component_definition of this Component.


        :return: The component_definition of this Component.
        :rtype: ComponentDefinition
        """
        return self._component_definition

    @component_definition.setter
    def component_definition(self, component_definition):
        """Sets the component_definition of this Component.


        :param component_definition: The component_definition of this Component.
        :type component_definition: ComponentDefinition
        """

        self._component_definition = component_definition
