# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from aifi.api.models.base_model_ import Model
from aifi.api.models.asset import Asset
from aifi.api.models.connection import Connection
from aifi.api.models.ui_setting import UiSetting
from aifi.api import util

from aifi.api.models.asset import Asset  # noqa: E501
from aifi.api.models.connection import Connection  # noqa: E501
from aifi.api.models.ui_setting import UiSetting  # noqa: E501

class DeviceFactory(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, label=None, api_configuration=None, version=None, assets=None, ui_settings=None, input=None, output=None):  # noqa: E501
        """DeviceFactory - a model defined in OpenAPI

        :param id: The id of this DeviceFactory.  # noqa: E501
        :type id: str
        :param label: The label of this DeviceFactory.  # noqa: E501
        :type label: str
        :param api_configuration: The api_configuration of this DeviceFactory.  # noqa: E501
        :type api_configuration: object
        :param version: The version of this DeviceFactory.  # noqa: E501
        :type version: str
        :param assets: The assets of this DeviceFactory.  # noqa: E501
        :type assets: List[Asset]
        :param ui_settings: The ui_settings of this DeviceFactory.  # noqa: E501
        :type ui_settings: List[UiSetting]
        :param input: The input of this DeviceFactory.  # noqa: E501
        :type input: List[Connection]
        :param output: The output of this DeviceFactory.  # noqa: E501
        :type output: List[Connection]
        """
        self.openapi_types = {
            'id': str,
            'label': str,
            'api_configuration': object,
            'version': str,
            'assets': List[Asset],
            'ui_settings': List[UiSetting],
            'input': List[Connection],
            'output': List[Connection]
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'api_configuration': 'apiConfiguration',
            'version': 'version',
            'assets': 'assets',
            'ui_settings': 'uiSettings',
            'input': 'input',
            'output': 'output'
        }

        self._id = id
        self._label = label
        self._api_configuration = api_configuration
        self._version = version
        self._assets = assets
        self._ui_settings = ui_settings
        self._input = input
        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceFactory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceFactory of this DeviceFactory.  # noqa: E501
        :rtype: DeviceFactory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this DeviceFactory.


        :return: The id of this DeviceFactory.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeviceFactory.


        :param id: The id of this DeviceFactory.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this DeviceFactory.


        :return: The label of this DeviceFactory.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this DeviceFactory.


        :param label: The label of this DeviceFactory.
        :type label: str
        """

        self._label = label

    @property
    def api_configuration(self):
        """Gets the api_configuration of this DeviceFactory.


        :return: The api_configuration of this DeviceFactory.
        :rtype: object
        """
        return self._api_configuration

    @api_configuration.setter
    def api_configuration(self, api_configuration):
        """Sets the api_configuration of this DeviceFactory.


        :param api_configuration: The api_configuration of this DeviceFactory.
        :type api_configuration: object
        """

        self._api_configuration = api_configuration

    @property
    def version(self):
        """Gets the version of this DeviceFactory.


        :return: The version of this DeviceFactory.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this DeviceFactory.


        :param version: The version of this DeviceFactory.
        :type version: str
        """

        self._version = version

    @property
    def assets(self):
        """Gets the assets of this DeviceFactory.


        :return: The assets of this DeviceFactory.
        :rtype: List[Asset]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this DeviceFactory.


        :param assets: The assets of this DeviceFactory.
        :type assets: List[Asset]
        """

        self._assets = assets

    @property
    def ui_settings(self):
        """Gets the ui_settings of this DeviceFactory.


        :return: The ui_settings of this DeviceFactory.
        :rtype: List[UiSetting]
        """
        return self._ui_settings

    @ui_settings.setter
    def ui_settings(self, ui_settings):
        """Sets the ui_settings of this DeviceFactory.


        :param ui_settings: The ui_settings of this DeviceFactory.
        :type ui_settings: List[UiSetting]
        """

        self._ui_settings = ui_settings

    @property
    def input(self):
        """Gets the input of this DeviceFactory.


        :return: The input of this DeviceFactory.
        :rtype: List[Connection]
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this DeviceFactory.


        :param input: The input of this DeviceFactory.
        :type input: List[Connection]
        """

        self._input = input

    @property
    def output(self):
        """Gets the output of this DeviceFactory.


        :return: The output of this DeviceFactory.
        :rtype: List[Connection]
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this DeviceFactory.


        :param output: The output of this DeviceFactory.
        :type output: List[Connection]
        """

        self._output = output
