# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from aifi.api.models.base_model_ import Model
from aifi.api.models.component_definition import ComponentDefinition
from aifi.api.models.key_value import KeyValue
from aifi.api.models.rack import Rack
from aifi.api import util

from aifi.api.models.component_definition import ComponentDefinition  # noqa: E501
from aifi.api.models.key_value import KeyValue  # noqa: E501
from aifi.api.models.rack import Rack  # noqa: E501

class Rig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, config=None, secrets=None, component_definitions=None, racks=None):  # noqa: E501
        """Rig - a model defined in OpenAPI

        :param config: The config of this Rig.  # noqa: E501
        :type config: List[KeyValue]
        :param secrets: The secrets of this Rig.  # noqa: E501
        :type secrets: List[KeyValue]
        :param component_definitions: The component_definitions of this Rig.  # noqa: E501
        :type component_definitions: List[ComponentDefinition]
        :param racks: The racks of this Rig.  # noqa: E501
        :type racks: List[Rack]
        """
        self.openapi_types = {
            'config': List[KeyValue],
            'secrets': List[KeyValue],
            'component_definitions': List[ComponentDefinition],
            'racks': List[Rack]
        }

        self.attribute_map = {
            'config': 'config',
            'secrets': 'secrets',
            'component_definitions': 'componentDefinitions',
            'racks': 'racks'
        }

        self._config = config
        self._secrets = secrets
        self._component_definitions = component_definitions
        self._racks = racks

    @classmethod
    def from_dict(cls, dikt) -> 'Rig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Rig of this Rig.  # noqa: E501
        :rtype: Rig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config(self):
        """Gets the config of this Rig.


        :return: The config of this Rig.
        :rtype: List[KeyValue]
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this Rig.


        :param config: The config of this Rig.
        :type config: List[KeyValue]
        """

        self._config = config

    @property
    def secrets(self):
        """Gets the secrets of this Rig.


        :return: The secrets of this Rig.
        :rtype: List[KeyValue]
        """
        return self._secrets

    @secrets.setter
    def secrets(self, secrets):
        """Sets the secrets of this Rig.


        :param secrets: The secrets of this Rig.
        :type secrets: List[KeyValue]
        """

        self._secrets = secrets

    @property
    def component_definitions(self):
        """Gets the component_definitions of this Rig.


        :return: The component_definitions of this Rig.
        :rtype: List[ComponentDefinition]
        """
        return self._component_definitions

    @component_definitions.setter
    def component_definitions(self, component_definitions):
        """Sets the component_definitions of this Rig.


        :param component_definitions: The component_definitions of this Rig.
        :type component_definitions: List[ComponentDefinition]
        """

        self._component_definitions = component_definitions

    @property
    def racks(self):
        """Gets the racks of this Rig.


        :return: The racks of this Rig.
        :rtype: List[Rack]
        """
        return self._racks

    @racks.setter
    def racks(self, racks):
        """Sets the racks of this Rig.


        :param racks: The racks of this Rig.
        :type racks: List[Rack]
        """

        self._racks = racks
